name: Assign to Pull Request
on:
  # Negeer commits die zijn gemaakt in:
  paths-ignore:
    - '.github/**'
    - 'extra/**'
    - '.vscode/**'
    - '.devcontainer/**'
    - 'README.md'
    - LICENSE
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  assign:
    name: Assign member
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: uesteibar/reviewer-lottery@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}