name: React run test
on:
    pull_request:
        branches:
            - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '10', '12', '14']
    
    name: Check Node version ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test